export const tiSynchronizationTableConfig = [
    { name: 'res_system_id', label: 'System ID', default: 'TRADE', type: 'String', length: 5 },
    { name: 'res_customer_id', label: 'Customer ID', type: 'String', length: 14 },
    { name: 'res_facility_id', label: 'Facility ID', type: 'String', length: 14 },
    { name: 'res_loan_acno', label: 'Loan Account Number', type: 'Numeric', length: 26 },
    { name: 'res_prin_amt', label: 'Principal OS', type: 'Numeric', length: 16, sample: '0000000500500.00' },

    { name: 'res_commit_cif1', length: 14, source: 'TI' },
    { name: 'res_commit_amt1', length: 16, source: 'TI' },
    { name: 'res_commit_cif2', length: 14, source: 'TI' },
    { name: 'res_commit_amt2', length: 16 },
    { name: 'res_commit_cif3', length: 14 },
    { name: 'res_commit_amt3', length: 16 },
    { name: 'res_commit_cif4', length: 14 },
    { name: 'res_commit_amt4', length: 16 },
    { name: 'res_commit_cif5', length: 14 },
    { name: 'res_commit_amt5', length: 16 },
    { name: 'res_commit_cif6', length: 14 },
    { name: 'res_commit_amt6', length: 16 },
    { name: 'res_commit_cif7', length: 14 },
    { name: 'res_commit_amt7', length: 16 },
    { name: 'res_commit_cif8', length: 14 },
    { name: 'res_commit_amt8', length: 16 },
    { name: 'res_commit_cif9', length: 14 },
    { name: 'res_commit_amt9', length: 16 },
    { name: 'res_commit_cif10', length: 14 },
    { name: 'res_commit_amt10', length: 16 },

    { name: 'res_commit_cif11', length: 14 },
    { name: 'res_commit_amt11', length: 16 },
    { name: 'res_commit_cif12', length: 14 },
    { name: 'res_commit_amt12', length: 16 },
    { name: 'res_commit_cif13', length: 14 },
    { name: 'res_commit_amt13', length: 16 },
    { name: 'res_commit_cif14', length: 14 },
    { name: 'res_commit_amt14', length: 16 },
    { name: 'res_commit_cif15', length: 14 },
    { name: 'res_commit_amt15', length: 16 },

    { name: 'res_currency_cd', label: 'Currency Code', type: 'String', length: 3 },
    { name: 'res_loan_status', length: 2}
];