export const tiUtilizationTableConfig = [
    { name: 'res_system_id', length: 5 },
    { name: 'res_customer_id', length: 14 },
    { name: 'res_facility_id', length: 14 },
    { name: 'res_loan_acno', length: 26 },
    { name: 'res_tran_status', length: 4 },
    { name: 'res_loan_curr', length: 3 },
    { name: 'res_loan_amt', length: 16 },
    { name: 'res_maker_id', length: 10 },
    { name: 'res_checker_id', length: 10 },
    { name: 'res_earref_no', length: 16 },

    { name: 'res_endo_cif1', length: 10, source: 'TI' },
    { name: 'res_endo_amt1', length: 16, source: 'TI' },
    { name: 'res_endo_cif2', length: 10, source: 'TI' },
    { name: 'res_endo_amt2', length: 16, source: 'TI' },
    { name: 'res_endo_cif3', length: 10, source: 'TI' },
    { name: 'res_endo_amt3', length: 16, source: 'TI' },
    { name: 'res_endo_cif4', length: 10, source: 'TI' },
    { name: 'res_endo_amt4', length: 16, source: 'TI' },
    { name: 'res_endo_cif5', length: 10, source: 'TI' },
    { name: 'res_endo_amt5', length: 16, source: 'TI' },
    { name: 'res_endo_cif6', length: 10, source: 'TI' },
    { name: 'res_endo_amt6', length: 16, source: 'TI' },
    { name: 'res_endo_cif7', length: 10, source: 'TI' },
    { name: 'res_endo_amt7', length: 16, source: 'TI' },
    { name: 'res_endo_cif8', length: 10, source: 'TI' },
    { name: 'res_endo_amt8', length: 16, source: 'TI' },
    { name: 'res_endo_cif9', length: 10, source: 'TI' },
    { name: 'res_endo_amt9', length: 16, source: 'TI' },
    { name: 'res_endo_cif10', length: 10, source: 'TI' },
    { name: 'res_endo_amt10', length: 16, source: 'TI' },
    { name: 'res_endo_cif11', length: 10, source: 'TI' },
    { name: 'res_endo_amt11', length: 16, source: 'TI' },
    { name: 'res_endo_cif12', length: 10, source: 'TI' },
    { name: 'res_endo_amt12', length: 16, source: 'TI' },
    { name: 'res_endo_cif13', length: 10, source: 'TI' },
    { name: 'res_endo_amt13', length: 16, source: 'TI' },
    { name: 'res_endo_cif14', length: 10, source: 'TI' },
    { name: 'res_endo_amt14', length: 16, source: 'TI' },
    { name: 'res_endo_cif15', length: 10, source: 'TI' },
    { name: 'res_endo_amt15', length: 16, source: 'TI' },
];